### PR TITLE
Replace all uses of posts where they should be 'topics'

### PR DESCRIPTION
**Pull request by benajaero**
Hampton, they are topics not posts. Posts are inside topics.

### CODE REVIEW

**Comment by benajaero** [comment]
Woah, I can merge. Wow.

**Comment by andybrwr** [comment]
yeah you're a member lol

**Comment by benajaero** [comment]
magic

**Comment by andybrwr** [comment]
ye

**Comment by haylinmoore** [comment]
Was this tested first?!?!

**Comment by benajaero** [comment]
ye

**Comment by benajaero** [comment]
The server url is /topics

**Pull request merged**
